@startuml
skinparam dpi 200

class ProfitRestController {
    +ProfitRestController()
    +Map<String, Object> getWeeklyProfit()
    +Map<String, Object> getMonthlyProfit()
}

class ProfitService {
    +ProfitService()
    +List<Profit> getWeeklyProfit()
    +List<Profit> getMonthlyProfit()
}

class RestHelper {
    +RestHelper()
    +Map<String, Object> serverError(Exception e)
    +Map<String, Object> sendJson(Map<String, Object> data)
}

ProfitRestController --> ProfitService : HasA
ProfitRestController --> RestHelper : HasA

@enduml